services:
  kapoot:
    build:
      context: .
    container_name: kapoot_site
    volumes:
      - ./private:/build/private
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
