version: '3.8'

services:
  kapoot:
    build:
      context: .
    container_name: kapoot_site
    volumes:
      - /home/kapoot/private:/build/private
    expose:
      - "8000"
    environment:
      - NODE_ENV=production
    networks:
      - shared-net
    restart: unless-stopped

networks:
  shared-net:
    external: true
